version: 2.1
orbs:
  # "cypress-io/cypress@3" installs the latest published
  # version "s.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@3.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@3
executors:
  default:
    description: |
      Single Docker container used to run Cypress Tests
    docker:
      - image: cimg/node:<< parameters.node-version >>-browsers
    parameters:
      node-version:
        default: 18.17.0
        description: |
          The version of Node to run your tests with.
        type: string
workflows:
  build:
    jobs:
      - cypress/run:
          cypress-command: npx wait-on@latest http://localhost:3000 && npx cypress run
          start-command: "npm run build && npm run start"
