version: 2.1

jobs:
  cypress-test:
    docker:
      - image: cimg/node:18.17.0-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build application
          command: npm run build
      - run:
          name: Start application
          command: |
            npm run start & npx wait-on http://localhost:3000
      - run:
          command: npx cypress run
workflows:
  build_and_test:
    jobs:
      - cypress-test
